### ISSUE TITLE
The prop value with an expression type of MetaProperty could not be resolved. Please file an issue ( https://github.com/jsx-eslint/jsx-ast-utils/issues/new ) to get this fixed immediately.

### ISSUE THREAD

**Issue by omozokelvin** [jsx-eslint/jsx-ast-utils#133] opened 2023-07-24 08:23 UTC

**Comment by ljharb** [comment] 2023-07-24 18:43
What code is causing this error? Presumably something like `import.meta.something`?

**Comment by ljharb** [comment] 2023-09-14 17:22
Closing as a duplicate of #119 (and #136)

**Closed by ljharb** 2023-09-14 17:22 UTC
