### ISSUE TITLE
JSXEmptyExpression could not be resolved

### ISSUE THREAD

**Issue by 7up-charsi** [jsx-eslint/jsx-ast-utils#144] opened 2024-12-06 13:32 UTC
The prop value with an expression type of JSXEmptyExpression could not be resolved. Please file an issue ( https://github.com/jsx-eslint/jsx-ast-utils/issues/new ) to get this fixed immediately.

```bash
$ npm ls jsx-ast-utils
eye-glasses@0.1.0 D:\eye-glasses
├─┬ eslint-config-next@15.0.3 invalid: "13.1.1" from node_modules/.pnpm/@paralleldrive+cuid2@2.2.2/node_modules/@paralleldrive/cuid2 -> .\node_modules\.pnpm\eslint-config-next@15.0.3_eslint@9.16.0_jiti@2.4.1__typescript@5.7.2\node_modules\eslint-config-next
│ ├─┬ eslint-plugin-jsx-a11y@6.10.2 -> .\node_modules\.pnpm\eslint-plugin-jsx-a11y@6.10.2_eslint@9.16.0_jiti@2.4.1_\node_modules\eslint-plugin-jsx-a11y
│ │ └── jsx-ast-utils@3.3.5 -> .\node_modules\.pnpm\jsx-ast-utils@3.3.5\node_modules\jsx-ast-utils
│ └─┬ eslint-plugin-react@7.37.2 -> .\node_modules\.pnpm\eslint-plugin-react@7.37.2_eslint@9.16.0_jiti@2.4.1_\node_modules\eslint-plugin-react    
│   └── jsx-ast-utils@3.3.5 -> .\node_modules\.pnpm\jsx-ast-utils@3.3.5\node_modules\jsx-ast-utils
├─┬ react-hook-form@7.53.2 -> .\node_modules\.pnpm\react-hook-form@7.53.2_react@19.0.0\node_modules\react-hook-form
│ └─┬ eslint-plugin-react@7.37.2 -> .\node_modules\.pnpm\eslint-plugin-react@7.37.2_eslint@9.16.0_jiti@2.4.1_\node_modules\eslint-plugin-react    
│   └── jsx-ast-utils@3.3.5 deduped -> .\node_modules\.pnpm\jsx-ast-utils@3.3.5\node_modules\jsx-ast-utils
└─┬ react-toastify@10.0.6 -> .\node_modules\.pnpm\react-toastify@10.0.6_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\react-toastify   
  └─┬ eslint-plugin-jsx-a11y@6.10.2 -> .\node_modules\.pnpm\eslint-plugin-jsx-a11y@6.10.2_eslint@9.16.0_jiti@2.4.1_\node_modules\eslint-plugin-jsx-a11y
    └── jsx-ast-utils@3.3.5 deduped -> .\node_modules\.pnpm\jsx-ast-utils@3.3.5\node_modules\jsx-ast-utils
```

**Comment by ljharb** [comment] 2024-12-06 18:43
Thanks, I think this is a duplicate of #137. Can you provide the code that this is erroring on?

**Comment by 7up-charsi** [comment] 2024-12-06 20:39
Hi @ljharb
i restarted my vscode and this error has gone. i will try to share more context when it appears again.

**Closed** 2024-12-06 20:48 UTC
