### ISSUE TITLE
The prop value with an expression type of TSNonNullExpression could not be resolved

### ISSUE THREAD

**Issue by Kaybarax** [jsx-eslint/jsx-ast-utils#124] opened 2022-12-05 01:34 UTC
"The prop value with an expression type of TSNonNullExpression could not be resolved" is shown when you run 
````
$ npm run precommit
````

**Comment by ljharb** [comment] 2022-12-05 06:03
What is that project-specific script? What version of jsx-ast-utils are you using?

**Comment by noyoliel-devocean** [comment] 2023-02-12 13:54
I started getting this after moving to react 18 from react 16. Not sure what it relates to

**Comment by ljharb** [comment] 2023-02-12 15:09
Ok, but what *is* the precommit npm script? That’s something in your own package.json.

**Comment by florian-lefebvre** [comment] 2023-03-11 18:01
I have the same issue, using husky precommit hook: `pnpm lint`. Here is the (mono)repo: https://github.com/op-ent/op-ent

**Comment by ljharb** [comment] 2023-03-11 21:08
@florian-lefebvre in your case, it's running via nx. can you reproduce it if you run with `npx eslint` directly?

**Comment by florian-lefebvre** [comment] 2023-03-12 12:05
I checked in which workspace the error happened and it's in the remix app. Doing either `pnpm --filter app lint` or `cd apps/app && pnpm lint` throws the error so I think it's not related to nx. What can I do to help you?

**Comment by ljharb** [comment] 2023-03-12 20:57
then can you cd into apps/app and run `npx eslint` directly?

**Comment by florian-lefebvre** [comment] 2023-03-13 19:40
It doesn't output anything

**Comment by ljharb** [comment] 2023-03-13 19:48
That's very strange, since I assume that's all `pnpm lint` is running.

When I check out the monorepo you linked, and run `pnpm install && pnpm lint`, everything passes.

**Comment by ljharb** [comment] 2023-03-13 19:50
Since @Kaybarax hasn't replied, nor has @noyoliel-devocean, and @florian-lefebvre's issue isn't reproducible, I'll close this, but happy to keep discussing, and will reopen if it repros.

**Closed by ljharb** 2023-03-13 19:50 UTC

**Comment by noyoliel-devocean** [comment] 2023-03-14 05:29
@ljharb I don't have any precommit hooks / npm precommit scripts as far as i'm aware.
It happens on local run of eslint. I get several of these messages without additional information in the logs.

**Comment by ljharb** [comment] 2023-03-14 05:33
@noyoliel-devocean if you can provide a repro repo i'd love to fix it :-)
