### ISSUE TITLE
The prop value with an expression type of AwaitExpression could not be resolved.

### ISSUE THREAD

**Issue by wasim-ullah** [jsx-eslint/jsx-ast-utils#130] opened 2023-06-30 00:43 UTC
Hi, I have this github repository https://github.com/wasim-ullah/blog which I am trying to deploy through vercel or netlify, it gives me the error that says: "The prop value with an expression type of AwaitExpression could not be resolved. Please file an issue ( https://github.com/jsx-eslint/jsx-ast-utils/issues/new ) to get this fixed immediately."

**Comment by ljharb** [comment] 2023-06-30 02:30
Are you perhaps using native ESM with a top-level await? If so, could you provide some of the code doing so?

**Comment by wasim-ullah** [comment] 2023-06-30 19:14
Hi, thanks for your response, please find the code here: https://github.com/wasim-ullah/blog

**Comment by ljharb** [comment] 2023-07-25 22:36
@wasim-ullah i see the code, but no way to reproduce the problem. `npx eslint --ext=js,jsx,mjs,ts,tsx .`, for example, works fine.

**Comment by david-abell** [comment] 2023-08-01 10:22
I've just encountered this same issue using Astro when a tag has an async import statement in its src prop.

` <img src={(await import('../assets/img/logo.svg')).default} alt="Your Logo" width="47" height="37" />`

The exact code is from here: https://github.com/markteekman/accessible-astro-starter/blob/b0c006e4f37175f99788ea4f6b966785680eb9ea/src/components/Navigation.astro#L9

**Comment by ljharb** [comment] 2023-08-05 03:04
@david-abell i'm not familiar with that format, but i would not expect *anything* to be able to lint it, since it's entirely nonstandard, unless it had a custom eslint parser. https://github.com/markteekman/accessible-astro-starter/blob/b0c006e4f37175f99788ea4f6b966785680eb9ea/.eslintrc.js#L24 seems inaccurate, since that code is definitely not normal TypeScript.

**Comment by ljharb** [comment] 2023-08-05 05:38
I'm going to have to close this since I can't reproduce it, and `.astro` is a nonstandard format that would need a custom eslint parser at a minimum to handle.

I'll be more than happy to reopen it if there's a way to reproduce it.

**Closed by ljharb** 2023-08-05 05:38 UTC
