### ISSUE TITLE
TSNonNullExpression could not be resolved

### ISSUE THREAD

**Issue by feeduraddiction** [jsx-eslint/jsx-ast-utils#127] opened 2023-04-18 13:54 UTC
Hi, during build we've got this message and fatal error after:

The prop value with an expression type of TSNonNullExpression could not be resolved. Please file an issue ( https://github.com/jsx-eslint/jsx-ast-utils/issues/new ) to get this fixed immediately.

**Comment by ljharb** [comment] 2023-04-18 17:30
What version of jsx-ast-utils do you have installed?

Do you happen to know what code you're linting that causes this error?

**Comment by jimmed** [comment] 2023-05-02 16:19
I'm also experiencing this issue in a private repo. I'm happy to provide more context as needed.

The issue is presenting in two different ways:

1. **Without `import type`**

   ```ts
   import { SomeTypeOrInterface } from "some-module";
   ```

   ```
   /path/to/my/app/file.tsx
   Error:   1:1  error  Type import "SomeTypeOrInterface" is used by decorator metadata  @typescript-eslint/consistent-type-imports
   ```
   
2. **With `import type`**

   ```ts
   import type { SomeTypeOrInterface } from "some-module";
   ```

   ```
   /path/to/my/app/file.tsx
   Error:   1:1  error  All imports in the declaration are only used as types. Use `import type`  @typescript-eslint/consistent-type-imports
   ```

**Comment by ljharb** [comment] 2023-05-31 18:49
@jimmed thanks! unfortunately our tests currently can't parse `import type` syntax. Is that the only cases where you're seeing "TSNonNullExpression could not be resolved"?

**Comment by ljharb** [comment] 2023-06-28 15:45
I wonder if #129 may fix this? I'm going to close it, and if the next release doesn't fix it (or if @feeduraddiction can provide repro info) then I'm happy to reopen it.

**Closed by ljharb** 2023-06-28 15:45 UTC
