### ISSUE TITLE
MetaProperty

### ISSUE THREAD

**Issue by jvanriel** [jsx-eslint/jsx-ast-utils#134] opened 2023-08-05 18:57 UTC
$ eslint src --ext ts,tsx --report-unused-disable-directives --max-warnings 0
The prop value with an expression type of MetaProperty could not be resolved. Please file an issue ( https://github.com/jsx-eslint/jsx-ast-utils/issues/new ) to get this fixed immediately.

**Comment by ljharb** [comment] 2023-08-05 19:18
Duplicate of #119. If you could comment there with the code that's erroring that'd be most helpful!

**Closed by ljharb** 2023-08-05 19:18 UTC
